import { type Listing } from './types'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    type: 'new',
    brand: 'Nike',
    model: 'Mercurial Vapor 16 Elite FG',
    terrain: 'FG',
    size: 42,
    width: 'standard',
    closure: 'laces',
    cut: 'low',
    playStyle: 'speed',
    playerProfile: 'confirmed',
    upper: 'synthetic',
    price: 189,
    images: [],
    sellerId: 'admin',
    createdAt: new Date(),
  },
  {
    id: '2',
    type: 'used',
    brand: 'adidas',
    model: 'Predator Elite FG',
    terrain: 'FG',
    size: 41,
    width: 'standard',
    closure: 'laces',
    cut: 'high',
    playStyle: 'control',
    playerProfile: 'confirmed',
    upper: 'synthetic',
    price: 72,
    originalPrice: 240,
    condition: 'very_good',
    images: [],
    sellerId: 'user1',
    createdAt: new Date(),
  },
  {
    id: '3',
    type: 'new',
    brand: 'Puma',
    model: 'Future 7 Ultimate FG/AG',
    terrain: 'FG',
    size: 43,
    width: 'standard',
    closure: 'laces',
    cut: 'low',
    playStyle: 'versatile',
    playerProfile: 'amateur',
    upper: 'knit',
    price: 219,
    images: [],
    sellerId: 'admin',
    createdAt: new Date(),
  },
  {
    id: '4',
    type: 'used',
    brand: 'Nike',
    model: 'Phantom GX Elite FG',
    terrain: 'FG',
    size: 44,
    width: 'standard',
    closure: 'laceless',
    cut: 'low',
    playStyle: 'control',
    playerProfile: 'elite',
    upper: 'microfiber',
    price: 85,
    originalPrice: 280,
    condition: 'good',
    images: [],
    sellerId: 'user2',
    createdAt: new Date(),
  },
  {
    id: '5',
    type: 'new',
    brand: 'New Balance',
    model: 'Furon v7 Pro FG',
    terrain: 'FG',
    size: 40,
    width: 'narrow',
    closure: 'laces',
    cut: 'low',
    playStyle: 'speed',
    playerProfile: 'confirmed',
    upper: 'synthetic',
    price: 145,
    images: [],
    sellerId: 'admin',
    createdAt: new Date(),
  },
  {
    id: '6',
    type: 'used',
    brand: 'adidas',
    model: 'Copa Pure 2 Elite FG',
    terrain: 'FG',
    size: 42,
    width: 'wide',
    closure: 'laces',
    cut: 'low',
    playStyle: 'control',
    playerProfile: 'confirmed',
    upper: 'leather',
    price: 110,
    originalPrice: 250,
    condition: 'very_good',
    images: [],
    sellerId: 'user3',
    createdAt: new Date(),
  },
  {
    id: '7',
    type: 'new',
    brand: 'Mizuno',
    model: 'Morelia Neo IV Beta Elite FG',
    terrain: 'FG',
    size: 43,
    width: 'standard',
    closure: 'laces',
    cut: 'low',
    playStyle: 'control',
    playerProfile: 'elite',
    upper: 'leather',
    price: 299,
    images: [],
    sellerId: 'admin',
    createdAt: new Date(),
  },
  {
    id: '8',
    type: 'used',
    brand: 'Puma',
    model: 'King Ultimate FG',
    terrain: 'FG',
    size: 41,
    width: 'standard',
    closure: 'laces',
    cut: 'low',
    playStyle: 'power',
    playerProfile: 'amateur',
    upper: 'leather',
    price: 60,
    originalPrice: 180,
    condition: 'good',
    images: [],
    sellerId: 'user4',
    createdAt: new Date(),
  },
]
